config/routes.rb
Rails.application.routes.draw do
  resources :pinxes

  devise_for :users
  root "pages#home"
  get "about" => "pages#about"

end

app/models/pinx.rb
class Pinx < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
   def about
   end
  
end

app/controllers/pinxes_controller.rb
class PinxesController < ApplicationController
  before_action :set_pinx, only: [:show, :edit, :update, :destroy]

  def index
    @pinxes = Pinx.all
  end


  def show
  end

 
  def new
    @pinx = Pinx.new
  end


  def edit
  end


  def create
    @pinx = Pinx.new(pinx_params)

   respond_to do |format|
      if @pinx.save
        redirect_to @pinx, notice: 'Pinx was successfully created.' 
       
      else
      render action: 'new'
      end
   end
  end

 
  def update
    respond_to do |format|
      if @pinx.update(pinx_params)
        format.html { redirect_to @pinx, notice: 'Pinx was successfully updated.' }
        format.json { render :show, status: :ok, location: @pinx }
      else
        format.html { render :edit }
        format.json { render json: @pinx.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @pinx.destroy
    respond_to do |format|
      format.html { redirect_to pinxes_url, notice: 'Pinx was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pinx
      @pinx = Pinx.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pinx_params
      params.require(:pinx).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pinxes_helper.rb
module PinxesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar  navbar-static=top navbar-default" role="navigation">
  <div class="container">
 
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Get it</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
    
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
	   <li><%= link_to "About", about_path %></li>
     
<% if user_signed_in? %>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>

     <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>


     <% else %>

     <li> <%= link_to "Sign in", new_user_session_path %> </li>

<% end %>






      </ul>
    </div><!-- /.navbar-collapse -->
</div> <!--container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
	
	<!-- equal sign is used when you want text on a page -->
	<% flash.each do |name, msg| %>
	
		<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
	
	<% end %>
	
	
	<%= yield %>

</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>This is the about part of this thing what?!</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
<h1>Welcome</h1>
<p>

<% if user_signed_in? %>
   # do something

<% else %>

<p>

<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
<%= link_to "Sign up" , new_user_registration_path, class:"btn btn-primary btn-lg" %>

</p>


<% end %>


</div>

app/views/pinxes/_form.html.erb
<%= form_for(@pinx) do |f| %>
  <% if @pinx.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pinx.errors.count, "error") %> prohibited this pinx from being saved:</h2>

      <ul>
      <% @pinx.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pinxes/edit.html.erb
<h1>Editing pinx</h1>

<%= render 'form' %>

<%= link_to 'Show', @pinx %> |
<%= link_to 'Back', pinxes_path %>

app/views/pinxes/index.html.erb
<h1>Listing pinxes</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pinxes.each do |pinx| %>
      <tr>
        <td><%= pinx.description %></td>
        <td><%= link_to 'Show', pinx %></td>
        <td><%= link_to 'Edit', edit_pinx_path(pinx) %></td>
        <td><%= link_to 'Destroy', pinx, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pinx', new_pinx_path %>

app/views/pinxes/new.html.erb
<h1>New pinx</h1>

<%= render 'form' %>

<%= link_to 'Back', pinxes_path %>

app/views/pinxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pinx.description %>
</p>

<%= link_to 'Edit', edit_pinx_path(@pinx) %> |
<%= link_to 'Back', pinxes_path %>